name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Устанавливаем flake8 и pytest для lint и тестирования
        pip install flake8 pytest
        # Устанавливаем зависимости из requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run linter (flake8)
      run: |
        # Проверка на синтаксические ошибки Python или не определённые переменные
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Выводит все ошибки как предупреждения, ограничение по сложности и длине строки
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests (pytest)
      run: |
        # Запуск всех тестов с использованием pytest
        pytest

    - name: Run bot
      run: |
        echo "Starting Telegram Bot..."
        
        # Отладочная информация
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        
        # Проверка наличия bot.py
        if [ ! -f "bot.py" ]; then
            echo "Error: bot.py not found!"
            exit 1
        fi
        
        # Запуск бота
        python bot.py

        # Ждём завершения выполнения
        echo "Bot stopped or crashed"
