name: Python Bot CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linter (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests (pytest)
        run: |
          pytest

  deploy:
    needs: test # Запускаем деплой только после успешного тестирования
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Восстанавливаем предыдущие фильтры
      - name: Download previous filters
        uses: actions/download-artifact@v3
        with:
          name: filter-data
          path: ./data
        continue-on-error: true

      # Запускаем бота
      - name: Run bot
        id: run_bot  # Добавляем id для отслеживания статуса
        continue-on-error: true  # Позволяем продолжить выполнение даже при ошибке
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          echo "Starting Telegram Bot..."
          python bot.py &
          
          # Даем боту время на инициализацию
          sleep 30
          
          # Проверяем, что бот все еще работает
          if ps aux | grep "[p]ython bot.py" > /dev/null; then
            echo "Bot is running, stopping gracefully..."
            kill $(ps aux | grep "[p]ython bot.py" | awk '{print $2}')
            exit 0
          else
            echo "Bot process not found!"
            exit 1
          fi

      # Сохраняем фильтры только если бот завершился с ошибкой
      - name: Upload filters
        if: steps.run_bot.outcome == 'failure'  # Выполняем только при ошибке
        uses: actions/upload-artifact@v3
        with:
          name: filter-data
          path: ./data/filters.db
          retention-days: 90
